Fix pydantic due to wrong default type
ghga-de/file-ingest-service pull request #20
Opened 2023-11-30 16:31 UTC by ckaipf

I am currently implementing the same in ekss, as it is testing the Vault config a type problem with the default None has occurred. Should we implement this as suggested in this PR or with Optional[str] and Optional[SecretStr] and defaulf is None?

2023-11-30 19:09 UTC, Cito requested changes
I'd rather leave `None` as default and change the type to `Optional[...]`.

2023-12-01 10:20 UTC, ckaipf commented on src/fis/adapters/outbound/vault/client.py
> +        elif config.vault_role_id and config.vault_secret_id:
Same as in ekss, `None` doesn't have method `get_secret_value()`

2023-12-01 15:24 UTC, Cito commented
Looks good now, but the openapi.yaml still needs to be updated.

2023-12-01 15:24 UTC, Cito approved these changes, later dismissed

2023-12-04 10:53 UTC, Cito approved these changes

2023-12-04 15:00 UTC, merged