Add configurable mount point for secret backend
ghga-de/file-ingest-service pull request #24
Opened 2024-03-04 09:21 UTC by ckaipf

## Objective

This pull request aims to enhance the functionality by introducing a new configuration parameter, `vault_secrets_mount`. The addition of this parameter will allow users to specify a different mount point for storing secrets, providing greater flexibility and organization within Vault.

## Updates

- Added the vault_secrets_mount parameter to the configuration and pass it to hvac.

2024-03-04 12:54 UTC, mephenor requested changes
One small thing regarding the config option.

Also, this should include at least a minor version bump, but probably even a major one, as changing the mount point is probably not backwards compatible

2024-03-04 12:54 UTC, mephenor commented on src/fis/adapters/outbound/vault/client.py
> +        examples=["secret"],
```suggestion
        default="file-secrets",
        examples=["file-secrets"],
```
`secret` is a bit too generic, as everything we store is a secret.
Not sure if `file_secrets` might be better or not

2024-03-04 13:56 UTC, ckaipf commented on src/fis/adapters/outbound/vault/client.py
> +        examples=["secret"],
I think the same. However, the default mount point for the HashiCorp Vault KV2 engine is `secret`. So I think we should leave it that way.

2024-03-04 13:57 UTC, mephenor commented on src/fis/adapters/outbound/vault/client.py
> +        examples=["secret"],
So the default case would be backwards compatible with what we have right now?

2024-03-05 15:52 UTC, mephenor approved these changes

2024-03-05 15:57 UTC, merged